name: shop_laptop_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/get
  get: ^4.6.5

  # https://pub.dev/packages/dio
  dio: ^5.1.2
  http: ^0.13.6

  # https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.2.0-beta-1

  # Localization
  # https://pub.dev/packages/localization
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/retrofit
  retrofit: '>=4.0.0 <5.0.0'
  logger: ^1.1.0 #for logging purpose

  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.0

  # DI
  # https://pub.dev/packages/get_it
  get_it: ^7.2.0

  # https://pub.dev/packages/injectable
  injectable: ^2.1.1

  # Support manager routers for Flutter.
  # https://pub.dev/packages/fluro
  fluro: ^2.0.5

  # https://pub.dev/packages/either_dart
  either_dart: ^0.4.0

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.1.0

  # Support multi languages
  # https://pub.dev/packages/intl
  intl: ^0.17.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.10

  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.13.0

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.5

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3

  flutter_rating_bar: ^4.0.1

  google_fonts: ^4.0.4

  flutter_slidable: ^3.0.0

  firebase_auth: ^4.6.1

  cloud_firestore: ^4.7.1

  flutter_native_splash: ^2.2.19

  # https://pub.dev/packages/pin_code_fields
  pin_code_fields: ^7.4.0

  # https://pub.dev/packages/calendar_date_picker2
  calendar_date_picker2: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # https://pub.dev/packages/build_runner
  build_runner:

  # Support generate for retrofit
  # https://pub.dev/packages/json_serializable
  retrofit_generator:
  json_serializable: ^6.3.1

  # Support generate for injectable_generator
  # https://pub.dev/packages/injectable_generator
  injectable_generator:

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/shop_item.json

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#ffffff"

  image: assets/images/img_background.png

  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_background.png"
  remove_alpha_ios: true
  min_sdk_android: 21
